# Generated by Django 4.0.6 on 2022-08-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_limit_date_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='date_saved',
        ),
    ]
