# Generated by Django 4.0.6 on 2022-08-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_limit_date_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='date_saved',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
