# Generated by Django 4.0.6 on 2022-08-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foradmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_limit',
            name='date_block',
        ),
    ]
