# Generated by Django 4.0.6 on 2022-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foradmin', '0002_remove_admin_limit_date_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_date_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_block', models.IntegerField()),
            ],
        ),
    ]
